/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quanlybanhang.view;

import quanlybanhang.control.Program;
import quanlybanhang.model.HoaDon;

/**
 *
 * @author Admin
 */
public class ThanhToan extends javax.swing.JDialog {

    /**
     * Creates new form ThanhToan
     */
    public ThanhToan(java.awt.Frame parent, boolean modal, HoaDon hd) {
        super(parent, modal);
        initComponents();
        MaHDInf.setText(hd.getMaHD());
        NgayInf.setText(Program.formatTimestamp(hd.getNgayLapHD()));
        BanInf.setText(hd.getMaBan());
        NhanVienInf.setText(DangNhap.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThongTinPanel = new javax.swing.JPanel();
        TTHoaDonPanel = new javax.swing.JPanel();
        ComName = new javax.swing.JLabel();
        MaHDLabel = new javax.swing.JLabel();
        NgayLabel = new javax.swing.JLabel();
        MaHDInf = new javax.swing.JLabel();
        NgayInf = new javax.swing.JLabel();
        BanLabel = new javax.swing.JLabel();
        BanInf = new javax.swing.JLabel();
        NhanVienInf = new javax.swing.JLabel();
        NhanVienLabel = new javax.swing.JLabel();
        DSMonPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TongKetPanel = new javax.swing.JPanel();
        ControlPanel = new javax.swing.JPanel();
        BackBtn = new javax.swing.JLabel();
        ConfirmBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thanh toán đơn hàng");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        TTHoaDonPanel.setBackground(new java.awt.Color(255, 255, 255));

        ComName.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        ComName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComName.setText("NHÀ HÀNG TUYẾT NGÂN");

        MaHDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MaHDLabel.setText("Mã HD:");

        NgayLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NgayLabel.setText("Ngày:");

        MaHDInf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaHDInf.setText("<MaHD place>");

        NgayInf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NgayInf.setText("<Ngay place>");

        BanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BanLabel.setText("Bàn:");

        BanInf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BanInf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BanInf.setText("<Ban place>");

        NhanVienInf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NhanVienInf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NhanVienInf.setText("<NV place>");

        NhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NhanVienLabel.setText("Nhân viên:");

        javax.swing.GroupLayout TTHoaDonPanelLayout = new javax.swing.GroupLayout(TTHoaDonPanel);
        TTHoaDonPanel.setLayout(TTHoaDonPanelLayout);
        TTHoaDonPanelLayout.setHorizontalGroup(
            TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ComName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TTHoaDonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaHDLabel)
                    .addComponent(NgayLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaHDInf, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(NgayInf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BanLabel)
                    .addComponent(NhanVienLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BanInf, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NhanVienInf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        TTHoaDonPanelLayout.setVerticalGroup(
            TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TTHoaDonPanelLayout.createSequentialGroup()
                .addComponent(ComName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TTHoaDonPanelLayout.createSequentialGroup()
                        .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaHDLabel)
                            .addComponent(MaHDInf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TTHoaDonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NgayLabel)
                            .addComponent(NgayInf)))
                    .addGroup(TTHoaDonPanelLayout.createSequentialGroup()
                        .addComponent(BanInf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NhanVienInf))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TTHoaDonPanelLayout.createSequentialGroup()
                        .addComponent(BanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NhanVienLabel)))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        DSMonPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout DSMonPanelLayout = new javax.swing.GroupLayout(DSMonPanel);
        DSMonPanel.setLayout(DSMonPanelLayout);
        DSMonPanelLayout.setHorizontalGroup(
            DSMonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        DSMonPanelLayout.setVerticalGroup(
            DSMonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        TongKetPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TongKetPanelLayout = new javax.swing.GroupLayout(TongKetPanel);
        TongKetPanel.setLayout(TongKetPanelLayout);
        TongKetPanelLayout.setHorizontalGroup(
            TongKetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        TongKetPanelLayout.setVerticalGroup(
            TongKetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ThongTinPanelLayout = new javax.swing.GroupLayout(ThongTinPanel);
        ThongTinPanel.setLayout(ThongTinPanelLayout);
        ThongTinPanelLayout.setHorizontalGroup(
            ThongTinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(ThongTinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TTHoaDonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DSMonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TongKetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongTinPanelLayout.setVerticalGroup(
            ThongTinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(ThongTinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ThongTinPanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(TTHoaDonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(DSMonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(TongKetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)))
        );

        ControlPanel.setBackground(new java.awt.Color(255, 255, 204));

        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackBtn.setText("Quay lại");
        BackBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackBtn.setOpaque(true);
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        ConfirmBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfirmBtn.setText("Xác nhận");
        ConfirmBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConfirmBtn.setOpaque(true);

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ControlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ThongTinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(698, Short.MAX_VALUE)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ThongTinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 47, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JLabel BanInf;
    private javax.swing.JLabel BanLabel;
    private javax.swing.JLabel ComName;
    private javax.swing.JLabel ConfirmBtn;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JPanel DSMonPanel;
    private javax.swing.JLabel MaHDInf;
    private javax.swing.JLabel MaHDLabel;
    private javax.swing.JLabel NgayInf;
    private javax.swing.JLabel NgayLabel;
    private javax.swing.JLabel NhanVienInf;
    private javax.swing.JLabel NhanVienLabel;
    private javax.swing.JPanel TTHoaDonPanel;
    private javax.swing.JPanel ThongTinPanel;
    private javax.swing.JPanel TongKetPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
